"""Génère les 25 notebooks de plans détaillés dans Notebook_2026/plans/.

Chaque notebook est un .md jupytext avec :
- Titre + description + role + dataset
- Plan détaillé section par section
- Pas de code exécuté (squelette à compléter)
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "Notebook_2026/plans"
OUT_DIR.mkdir(parents=True, exist_ok=True)

JUPYTEXT_HEADER = """---
jupyter:
  jupytext:
    formats: ipynb,md
    text_representation:
      extension: .md
      format_name: markdown
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---
"""


def cell(content: str) -> str:
    return f"\n<!-- #region -->\n{content}\n<!-- #endregion -->\n"


def code_cell(content: str) -> str:
    return f"\n```python\n{content}\n```\n"


def build_notebook(title: str, role: str, dataset: str, intro: str,
                   sections: list[tuple[str, str]], sources: list[str]) -> str:
    """Construit le markdown d'un notebook complet.

    sections : liste de (titre, plan).
    """
    parts = [JUPYTEXT_HEADER]
    parts.append(cell(f"# {title}"))
    parts.append(cell(
        f"**Rôle visé** : {role}\n\n"
        f"**Dataset(s)** : {dataset}\n\n"
        f"{intro}\n\n"
        f"> Ce notebook est un **plan détaillé** des sections à aborder. "
        f"Le code reste à implémenter — voir `00_critique.md` pour la priorisation."
    ))

    for i, (sec_title, sec_plan) in enumerate(sections, start=1):
        parts.append(cell(f"## {i}. {sec_title}"))
        parts.append(cell(sec_plan))

    parts.append(cell(f"## {len(sections) + 1}. Sources"))
    src_list = "\n".join(f"- {s}" for s in sources)
    parts.append(cell(src_list))

    return "".join(parts)


# =============================================================================
# Définition des 25 notebooks
# =============================================================================

NOTEBOOKS: list[dict] = [

    # --- DS (5) ---
    {
        "filename": "DS_Causal_Inference",
        "title": "🔗 Causal Inference",
        "role": "Data Scientist · Wiki + Tutoriel",
        "dataset": "Lalonde (NSW job training), STAR (éducation)",
        "intro": "Inférence causale : passer de la corrélation à la causalité, base nécessaire pour tout impact mesurement, A/B testing, économétrie ou recommandation rigoureuse.",
        "sections": [
            ("Causalité vs Corrélation",
             "**Notions** :\n- Paradoxe de Simpson (avec exemple chiffré)\n- Paradoxe de Berkson (sélection sur collider)\n- Confondants observés vs non observés\n- Pourquoi un fit ML supervisé n'est PAS de la causalité\n\n**Code visé** : exemple Simpson sur dataset jouet + graphe.\n"),
            ("Causal DAGs et Do-Calculus (Pearl)",
             "**Notions** :\n- Notation DAG : `X → Y`, `Z → X, Z → Y` (confounder)\n- Backdoor criterion (quels Z conditionner)\n- Frontdoor criterion (alternative quand backdoor impossible)\n- Intervention `do(X=x)` vs observation `P(Y|X=x)`\n\n**Code visé** : `dowhy` ou `causal-learn` — construire un DAG, identifier l'effet."),
            ("A/B testing rigoureux",
             "**Notions** :\n- Hypothèse nulle, test bilatéral/unilatéral\n- Puissance statistique, MDE (Minimum Detectable Effect)\n- Sample size calculator (binary, continuous)\n- Test séquentiel vs fixed horizon\n- Peeking problem\n\n**Code visé** : `statsmodels` ou `scipy.stats` pour le test + calculator."),
            ("DiD — Differences-in-Differences",
             "**Notions** :\n- Quasi-expérience : `effect = (Y_treated_post - Y_treated_pre) - (Y_control_post - Y_control_pre)`\n- Hypothèse de tendances parallèles\n- Two-way fixed effects regression\n\n**Code visé** : régression OLS avec interactions, `linearmodels`."),
            ("Propensity Score Matching et IPW",
             "**Notions** :\n- Estimer `e(X) = P(T=1|X)` (LogReg ou GBM)\n- Matching : 1-NN, k-NN, caliper\n- Inverse Probability Weighting (IPW)\n- Doubly Robust estimators\n\n**Code visé** : `causalml` ou `econml`."),
            ("Synthetic Control",
             "**Notions** :\n- Construire une 'unité contrôle synthétique' par pondération\n- Cas d'usage : effet d'une loi sur un pays (Abadie)\n- Hypothèses\n\n**Code visé** : `pysyncon` ou `causalpy`."),
            ("DoubleML et Causal Forest",
             "**Notions** :\n- Athey & Imbens — apprentissage statistique pour causalité\n- Double ML : enlever le bias via 2 modèles ML (nuisance functions)\n- Causal Forest : RF qui partitionne par hétérogénéité du traitement\n- Heterogeneous Treatment Effects (HTE / CATE)\n\n**Code visé** : `EconML.dml`, `econml.grf`."),
            ("Instrumental Variables (2SLS)",
             "**Notions** :\n- Quand : confondants non observés, IV satisfait exclusion restriction\n- Two-Stage Least Squares\n- Force de l'instrument (F-stat)\n- Cas réel : RCT vs natural experiment\n\n**Code visé** : `linearmodels.IV2SLS`."),
            ("Mediation analysis",
             "**Notions** :\n- `X → M → Y` : effet direct vs indirect\n- Decomposition : NDE, NIE (Natural Direct / Indirect Effect)\n- Pearl mediation formula\n\n**Code visé** : `causaleffect` ou implémentation manuelle."),
            ("Frameworks 2026 et pièges",
             "**Notions** :\n- Libs : `dowhy` (Microsoft), `econml` (Microsoft), `causalml` (Uber), `causal-learn` (CMU)\n- Pièges : confounders cachés, sensitivity analysis, p-hacking"),
        ],
        "sources": [
            "[Pearl — Causality (livre)](http://bayes.cs.ucla.edu/BOOK-2K/)",
            "[DoWhy docs](https://www.pywhy.org/dowhy/)",
            "[EconML docs](https://econml.azurewebsites.net/)",
            "[Causal Inference: The Mixtape (Cunningham)](https://mixtape.scunning.com/)",
            "Notebooks liés : `DS_Bayesian`, `MLE_AB_Testing`.",
        ],
    },

    {
        "filename": "DS_Bayesian",
        "title": "🎲 Bayesian Data Science",
        "role": "Data Scientist · Wiki + Tutoriel",
        "dataset": "Eight Schools (classique), Cal Housing",
        "intro": "Approche bayésienne : modélisation avec incertitude explicite, priors informatifs, hiérarchies. Indispensable quand petit échantillon, besoin d'IC, ou modèle interprétable structurellement.",
        "sections": [
            ("Pourquoi bayésien en 2026",
             "**Notions** :\n- Incertitude paramétrique vs prédictive\n- Priors : injection de connaissance experte\n- Régularisation naturelle (vs L1/L2 ad-hoc)\n- Hiérarchies : partial pooling (sweet spot biais/variance)\n- Quand préférer fréquentiste : très grandes data, baseline ML"),
            ("Bayes en un paragraphe",
             "**Notions** :\n- `P(θ|D) ∝ P(D|θ) P(θ)` (Bayes rule)\n- Posterior = likelihood × prior / evidence\n- Posterior predictive : `P(y_new|D) = ∫ P(y_new|θ) P(θ|D) dθ`\n- Pourquoi MCMC : intégrales hautes dim impossibles à calculer analytiquement"),
            ("Conjugate priors — cas simples",
             "**Notions** :\n- Beta-Binomial (taux de conversion)\n- Normal-Normal (moyenne d'une mesure)\n- Gamma-Poisson\n- Inverse-Gamma — Normal\n\n**Code visé** : calculer le posterior analytiquement pour 2 exemples."),
            ("MCMC — Metropolis, Gibbs, HMC, NUTS",
             "**Notions** :\n- Metropolis-Hastings : règle d'acceptation\n- Gibbs : sampling conditionnel\n- HMC : Hamiltonian Monte Carlo (gradient-based)\n- NUTS : No-U-Turn Sampler (HMC adaptatif)\n- Convergence : Rhat, ESS, trace plots"),
            ("PyMC v5+ — workflow complet",
             "**Notions** :\n- Définition du modèle (`with pm.Model()`)\n- Priors, likelihood, posterior\n- `pm.sample()` (NUTS par défaut)\n- `arviz` pour diagnostics et viz (trace, posterior plots, energy plot)\n\n**Code visé** : régression linéaire bayésienne + interprétation."),
            ("NumPyro (JAX-based)",
             "**Notions** :\n- Plus rapide que PyMC (JIT JAX)\n- Modèle = fonction Python\n- API stochastique avec `numpyro.sample`\n- `MCMC(NUTS, ...).run(...)`\n\n**Code visé** : même modèle reproduit, comparaison vitesse."),
            ("Variational Inference (ADVI)",
             "**Notions** :\n- Quand MCMC est trop lent\n- ADVI : Automatic Differentiation VI\n- Mean-field vs full-rank approximation\n- Trade-off : rapide mais biais sur les queues"),
            ("Hierarchical models — Eight Schools",
             "**Notions** :\n- Le modèle classique de Gelman\n- Partial pooling vs no pooling vs complete pooling\n- Funnel-shaped posterior (problème + reparam)\n- Cas d'usage : effets multi-niveaux (élèves dans classes dans écoles)"),
            ("Posterior predictive checks",
             "**Notions** :\n- Comparer données simulées vs réelles\n- p-values bayésiennes\n- Détection de model misspecification"),
            ("Bayesian A/B testing",
             "**Notions** :\n- Posterior sur `θ_A - θ_B`\n- `P(θ_B > θ_A | data)` directement interprétable\n- Loss function : risque attendu, stop rule\n- Lien avec `MLE_AB_Testing`"),
        ],
        "sources": [
            "[Statistical Rethinking — McElreath (livre + lectures YouTube)](https://xcelab.net/rm/statistical-rethinking/)",
            "[PyMC docs](https://www.pymc.io/)",
            "[NumPyro docs](https://num.pyro.ai/)",
            "[ArviZ docs](https://python.arviz.org/)",
            "Notebooks liés : `DS_Causal_Inference`, `MLE_AB_Testing`.",
        ],
    },

    {
        "filename": "DS_Geospatial",
        "title": "🗺️ Geospatial Data Science",
        "role": "Data Scientist · Wiki + Tutoriel",
        "dataset": "NYC Taxi (lat/lon), Natural Earth, OpenStreetMap",
        "intro": "Analyse de données géospatiales : projections, jointures spatiales, viz cartographiques, ML géo.",
        "sections": [
            ("Cadrer : projections, CRS, géodésie",
             "Notions : EPSG, WGS84 (4326), Web Mercator (3857), Lambert93 (FR), latlon vs xy. Transformation entre CRS avec `pyproj`."),
            ("GeoPandas — la lib de référence",
             "GeoSeries, GeoDataFrame, geometry column. Lecture shapefile / GeoJSON / GeoPackage. Code visé : load + plot."),
            ("Shapely — primitives géométriques",
             "Point, LineString, Polygon, MultiPolygon. Opérations : intersection, union, difference, buffer, convex hull, distance."),
            ("Spatial joins",
             "`gpd.sjoin` avec predicates : within, intersects, contains, touches, nearest. Cas : associer chaque point taxi à son borough."),
            ("Indexation spatiale",
             "R-tree, k-d tree, `rtree`. Pourquoi indispensable sur > 100k géométries."),
            ("Visualisation cartographique",
             "`folium` (Leaflet, interactif), `geoplot` (statique stat), `plotly.express` (choropleth/mapbox), `kepler.gl` (super avancé)."),
            ("Géocodage",
             "`geopy` : Nominatim (OSM gratuit), Google Maps API. Rate limits, caching."),
            ("Raster vs vector",
             "Vector : points/lignes/polygones. Raster : grille de pixels (satellite). `rasterio`, NetCDF, xarray pour multi-band."),
            ("DuckDB spatial + PostGIS",
             "DuckDB extension spatial = mini PostGIS embedded. PostGIS pour stack serveur. ST_* fonctions."),
            ("ML géospatial",
             "Features : distance to X, density grid, kNN-density. Choropleth aggregation. Graph Neural Networks sur routes."),
            ("H3 (Uber) hexagons",
             "Indexation hiérarchique de la sphère par hexagones. Idéal pour aggregation grids uniformes."),
        ],
        "sources": [
            "[GeoPandas docs](https://geopandas.org/)",
            "[Shapely docs](https://shapely.readthedocs.io/)",
            "[H3 Uber](https://h3geo.org/)",
            "[Geocomputation with Python](https://py.geocompx.org/)",
        ],
    },

    {
        "filename": "DS_Survival_Analysis",
        "title": "⏳ Survival Analysis",
        "role": "Data Scientist · Wiki + Tutoriel",
        "dataset": "Telco churn, ROSSi recidivism, NCCTG lung cancer",
        "intro": "Analyse de survie : prédire le temps avant un événement (churn, défaillance, décès) avec censure.",
        "sections": [
            ("Pourquoi survival (vs classification binaire)",
             "Notion clé : **censure à droite** (l'event n'a pas eu lieu à la fin du suivi). Ignorer la censure = biais. Cas : qui churne et **quand**."),
            ("Kaplan-Meier curves",
             "Estimateur non-paramétrique. Survival function S(t). Cas : comparer 2 groupes (homme/femme, traitement A/B)."),
            ("Log-rank test",
             "Tester si 2 courbes KM diffèrent significativement. H0 = même hazard."),
            ("Cox Proportional Hazards",
             "Modèle semi-paramétrique : `h(t|X) = h_0(t) exp(β^T X)`. Coefficients interprétables comme hazard ratios."),
            ("Vérifier l'hypothèse PH",
             "Schoenfeld residuals. Que faire si non respectée : stratification, time-varying covariates, AFT."),
            ("AFT models",
             "Accelerated Failure Time : `log(T) = β^T X + σε`. Plus simple à interpréter (effet sur le temps de survie)."),
            ("Random Survival Forest",
             "RF adapté à la censure. `scikit-survival`. Importance des features."),
            ("DeepSurv et DeepHit",
             "Neural Cox. Permet interactions non-linéaires + features riches. `pycox`."),
            ("XGBoost / LightGBM Survival",
             "`XGBoostSurvivalEmbeddings`, `LightGBM` avec `objective='regression:cox'`."),
            ("Évaluation",
             "C-index (concordance), Brier score time-dependent, Integrated Brier Score, calibration."),
            ("Cas d'usage",
             "Churn prediction (telco), équipement / défaillance (lien `TS_Maintenance_Predictive`), médical (cohortes)."),
        ],
        "sources": [
            "[lifelines docs](https://lifelines.readthedocs.io/)",
            "[scikit-survival docs](https://scikit-survival.readthedocs.io/)",
            "[Statistical methods for survival data — Klein & Moeschberger (livre)](https://www.springer.com/)",
        ],
    },

    {
        "filename": "DS_Recommender_Systems",
        "title": "🎬 Recommender Systems",
        "role": "Data Scientist + AI Engineer · Wiki + Tutoriel",
        "dataset": "MovieLens 1M / 25M, Amazon reviews",
        "intro": "Systèmes de recommandation : du baseline collaborative filtering aux modèles 2026 (transformer / LLM-based).",
        "sections": [
            ("Cadre",
             "Explicit (ratings 1-5) vs implicit (clicks, views, time spent). Sparse matrix users × items. Métriques en ligne (CTR) vs offline."),
            ("Baselines",
             "Popularité (most-watched), item-item top similar (cosine over items), user-user. Souvent baselines très fortes."),
            ("Collaborative Filtering KNN",
             "User-KNN, Item-KNN. Memory-based vs model-based. Lib : `surprise`."),
            ("Matrix Factorization — SVD, ALS, NMF",
             "Décomposition U×V^T avec rangs latents. SGD vs ALS. Implicit-feedback ALS (Hu 2008)."),
            ("Deep Learning",
             "Neural CF (NCF, He 2017), Wide & Deep, DeepFM. Embeddings users/items + MLP."),
            ("Two-Tower models",
             "YouTube DNN, Facebook EBR. User tower + item tower, similarity au runtime. Sert le retrieval ANN."),
            ("Sequential recommenders",
             "SASRec (Self-Attention), BERT4Rec, Transformer4Rec (NVIDIA). Capturer l'ordre des actions."),
            ("LLM-based recommenders (2024-2026)",
             "Approche : retrieve top-N via embeddings + reranking via LLM. P5 (Google), LLaRA, RecLM. Cold start beaucoup plus facile."),
            ("Évaluation offline",
             "Precision@k, Recall@k, NDCG, MRR, Hit Rate, Coverage, Novelty, Diversity. Leave-one-out vs random split."),
            ("Cold start et exploration/exploitation",
             "Bandits contextuels (LinUCB, Thompson sampling). Hybrides content + collaborative."),
            ("Stack 2026",
             "Libs : `implicit`, `lightfm`, `surprise`, `recbole`, `nvidia/merlin`, `recommenders` (Microsoft)."),
        ],
        "sources": [
            "[Microsoft Recommenders — repos](https://github.com/microsoft/recommenders)",
            "[RecBole](https://recbole.io/)",
            "[Merlin — NVIDIA](https://github.com/NVIDIA-Merlin/Merlin)",
            "[Awesome RecSys](https://github.com/jihoo-kim/awesome-RecSys)",
        ],
    },

    # --- DE (5) ---
    {
        "filename": "DE_PySpark",
        "title": "🔥 PySpark — Big Data Processing",
        "role": "Data Engineer · Tutoriel",
        "dataset": "NYC Taxi parquet (gros volume)",
        "intro": "PySpark pour le traitement distribué de gros volumes (≥ 100 GB). Comparatif avec Polars / DuckDB.",
        "sections": [
            ("Architecture Spark",
             "Driver + executors + cluster manager (YARN/Kubernetes/Standalone). RDD vs DataFrame vs Dataset. Lazy evaluation + DAG."),
            ("PySpark DataFrame API",
             "select, filter, groupBy, agg, join, window. Idiome : tout chaîner avant `.show()` ou `.collect()`."),
            ("SQL via spark.sql",
             "Registrer un DataFrame comme view temporaire puis SQL. Bonnes pratiques."),
            ("UDFs",
             "Python UDF (lent — serialization), Pandas UDF (vectorisé, beaucoup plus rapide), SQL UDF."),
            ("Partitioning et bucketing",
             "Partition par colonne pour pushdown filter. Bucketing pour optim joins."),
            ("Catalyst optimizer",
             "EXPLAIN, PARSED plan vs OPTIMIZED. Comment lire un plan."),
            ("Performance",
             "Broadcast joins (petite table), shuffle vs broadcast, skew handling, salt key, coalesce vs repartition."),
            ("Structured Streaming",
             "Streaming sur Kafka, micro-batch, exactly-once, watermark."),
            ("Spark ML — pyspark.ml",
             "Pipeline + Estimator + Transformer. Fit / transform sur DataFrame."),
            ("Delta Lake",
             "ACID sur S3, time travel, schema evolution, CDC. Alternative : Iceberg, Hudi."),
            ("Spark vs alternatives 2026",
             "Spark reste roi pour > 1 TB / cluster. Polars / DuckDB gagnent en single-machine. Daft (Python-native distributed)."),
        ],
        "sources": [
            "[Spark docs](https://spark.apache.org/docs/latest/)",
            "[Learning Spark 2nd ed (Databricks free)](https://www.databricks.com/p/ebook/learning-spark-from-oreilly)",
            "[Delta Lake docs](https://docs.delta.io/)",
        ],
    },

    {
        "filename": "DE_Airflow_Prefect",
        "title": "🌬️ Orchestration — Airflow / Prefect / Dagster",
        "role": "Data Engineer + MLOps · Wiki + Tutoriel",
        "dataset": "Pipeline ELT démo sur Cal Housing",
        "intro": "Orchestration de workflows : comparatif Airflow vs Prefect vs Dagster, patterns et bonnes pratiques 2026.",
        "sections": [
            ("Cadre orchestration",
             "DAG (Directed Acyclic Graph), task, scheduler, executor. Pourquoi pas juste cron : retry, dépendances, observabilité, backfill."),
            ("Apache Airflow 2.x",
             "DAG file Python, Operators (BashOperator, PythonOperator, KubernetesPodOperator), Sensors (attendre un évent), XCom (passage de data), Pools (concurrence)."),
            ("TaskFlow API (Airflow 2+)",
             "Décorateur `@task` qui rend les DAGs beaucoup plus pythoniques. Type-checked. XCom implicite."),
            ("Prefect 2/3",
             "Flow + tasks, deployment, blocks, work pools. Plus moderne mais moins mature qu'Airflow."),
            ("Dagster",
             "Software Defined Assets (SDA) : pense en termes de *données produites* plutôt que de tâches. Type-safe, asset materialization."),
            ("Argo Workflows",
             "Kubernetes-native, YAML DAG. Pour stack K8s."),
            ("Comparatif 2026",
             "Airflow : éprouvé, communauté massive, UI vieillissante. Prefect : moderne, cloud-first. Dagster : pour data engineers pointus. Tableau : adoption, scalabilité, courbe d'apprentissage."),
            ("Patterns",
             "Retry exponentiel, backfill (rejouer le passé), branching (skip si condition), dynamic mapping (N tâches en parallèle)."),
            ("Monitoring & alerting",
             "Slack/PagerDuty integration, SLA misses, métriques Prometheus."),
            ("ML pipelines",
             "Combine MLflow + orchestrateur : training pipeline = Airflow DAG qui appelle MLflow log_model."),
            ("Best practices",
             "Idempotence (tâche rejouable), atomic checkpoints, secrets en KMS, tests des DAGs."),
        ],
        "sources": [
            "[Airflow docs](https://airflow.apache.org/docs/)",
            "[Prefect docs](https://docs.prefect.io/)",
            "[Dagster docs](https://docs.dagster.io/)",
            "Notebook lié : `MLOps_Pipelines_Airflow`.",
        ],
    },

    {
        "filename": "DE_Kafka_Streaming",
        "title": "📡 Kafka — Event-Driven Streaming",
        "role": "Data Engineer · Wiki + Tutoriel",
        "dataset": "Synthetic event stream (générateur Python)",
        "intro": "Kafka pour les architectures event-driven : pub/sub à haute volumétrie, exactly-once, schema evolution.",
        "sections": [
            ("Cadre messaging",
             "Queues (1 consommateur) vs pub/sub (N consommateurs). Synchrone vs asynchrone. Push vs pull."),
            ("Architecture Kafka",
             "Brokers, topics, partitions, replicas, ISR. Consumers in consumer groups. Offsets."),
            ("Producer / Consumer Python",
             "`confluent-kafka-python` (perf maximale) ou `kafka-python` (pure Python). Code visé : producer continu + consumer manuel."),
            ("Schema Registry",
             "Avro / Protobuf / JSON Schema. Évolution forward/backward compatible. Confluent Schema Registry."),
            ("Kafka Streams + ksqlDB",
             "Stream processing dans la JVM. ksqlDB : SQL sur stream. Alternative : Flink."),
            ("Kafka Connect",
             "Source connectors (DB → Kafka) et Sink connectors (Kafka → DB/S3). CDC avec Debezium."),
            ("Faust (Python streaming)",
             "Frame Kafka Streams en Python. Async natif. Bon pour ML inference streaming."),
            ("Alternatives 2026",
             "Apache Pulsar (multi-tenant), Redpanda (Kafka-compatible Rust), RabbitMQ (AMQP, plus queue que stream), NATS (pub/sub léger)."),
            ("Event-driven architecture",
             "CQRS, event sourcing, eventual consistency. Patterns Outbox / Saga."),
            ("Streaming ML",
             "Online learning via `River`. Predictions streamées sur Kafka. Drift detection en stream."),
            ("Patterns",
             "Exactly-once semantics (transactions Kafka), idempotent producers, deduplication, dead-letter queue."),
        ],
        "sources": [
            "[Kafka docs](https://kafka.apache.org/documentation/)",
            "[Confluent Developer](https://developer.confluent.io/)",
            "[Faust docs](https://faust.readthedocs.io/)",
            "[Kafka: The Definitive Guide (livre Confluent free)](https://www.confluent.io/resources/kafka-the-definitive-guide/)",
        ],
    },

    {
        "filename": "DE_dbt_Modeling",
        "title": "🛠️ dbt — Transformation SQL versionnée",
        "role": "Data Engineer · Wiki + Tutoriel",
        "dataset": "NYC Taxi parquet via DuckDB ou Postgres",
        "intro": "dbt (data build tool) : SQL-first ELT, tests, documentation auto, version contrôlé. Standard 2024+ pour la transformation analytique.",
        "sections": [
            ("Pourquoi dbt",
             "Tournant du data warehouse moderne : ELT (transformations dans le DW, pas en amont). Versioning, tests, docs auto. Communauté + écosystème énorme."),
            ("Pattern staging → intermediate → mart",
             "Layers : `stg_*` (parsing brut), `int_*` (jointures et nettoyage), `fct_*` / `dim_*` (vue business). Modularité."),
            ("Materialization",
             "`view` (rapide à créer), `table` (rapide à query), `incremental` (append/merge), `ephemeral` (CTE inline)."),
            ("Tests",
             "Built-in : `unique`, `not_null`, `accepted_values`, `relationships`. Custom tests via SQL. Singular vs generic tests."),
            ("Sources et freshness",
             "Declarer les sources (tables raw). `dbt source freshness` pour alerter si data stale."),
            ("Macros + Jinja",
             "Réutilisation de SQL. Macros utilitaires (`dbt_utils`, `dbt_expectations`)."),
            ("Documentation auto-générée",
             "`dbt docs generate && dbt docs serve` → site web avec lineage + descriptions."),
            ("dbt + DuckDB en local",
             "`dbt-duckdb` : dev en local sans Snowflake/BQ. Migration vers prod sans changer le SQL."),
            ("Cloud DWs : Snowflake / BigQuery / Postgres",
             "Adapter par moteur. Particularités : permissions, scaling, coût."),
            ("Comparatif 2026",
             "dbt Core (OSS) vs dbt Cloud (SaaS) vs **SQLMesh** (nouvelle alternative — versioning automatique, plus rapide) vs **Dataform** (Google)."),
            ("CI/CD pour dbt",
             "GitHub Actions : `dbt build` sur PR, slim CI (`--state`)."),
        ],
        "sources": [
            "[dbt docs](https://docs.getdbt.com/)",
            "[Analytics Engineering with dbt — Madison Mae](https://www.oreilly.com/)",
            "[SQLMesh docs](https://sqlmesh.readthedocs.io/)",
        ],
    },

    {
        "filename": "DE_Data_Quality",
        "title": "✅ Data Quality — tests, monitoring, contracts",
        "role": "Data Engineer + MLOps · Wiki + Tutoriel",
        "dataset": "Titanic + Cal Housing",
        "intro": "Garantir la qualité des données : profiling, tests, contracts, observability.",
        "sections": [
            ("6 dimensions de la qualité",
             "Completeness, uniqueness, validity, accuracy, consistency, timeliness. Examples concrets."),
            ("Great Expectations 1.x (2024+)",
             "Expectations declaratives. Suites de tests. Data docs HTML. Integration Airflow."),
            ("Soda Core / Soda Cloud",
             "Alternative à GE, plus léger. SodaCL — DSL de tests data."),
            ("Pandera — schema validation",
             "Type-safe DataFrame schemas. Decorator pour valider à l'entrée/sortie de fonctions."),
            ("Pydantic pour structured data",
             "Validation des configs, payloads API. Type coercion automatique."),
            ("Profiling automatique",
             "`ydata-profiling` (HTML report), `dataprep.eda` (rapide via Dask), `sweetviz` (comparaison train/test)."),
            ("Data observability",
             "Monte Carlo, Anomalo, Datafold, Lightup. Détectent freshness, volume, distribution drift automatiquement."),
            ("Schema drift detection",
             "Nouveau champ, type changé, valeurs nulles apparues. Tools : Datafold, dbt schema tests."),
            ("Data contracts",
             "Concept : producer s'engage sur le schéma + SLA. Enforcement via CI dbt/Pandera. Initiatives : Atlan, Acryl."),
            ("Tests dans le pipeline",
             "Pattern Airflow : task `validate_with_GE` qui FAIL la DAG si tests rouges. Quarantine flow."),
            ("Lineage",
             "OpenLineage (CNCF standard), DataHub, Marquez, OpenMetadata. Suivi automatique des transformations."),
        ],
        "sources": [
            "[Great Expectations docs](https://docs.greatexpectations.io/)",
            "[Soda docs](https://docs.soda.io/)",
            "[Pandera docs](https://pandera.readthedocs.io/)",
            "[OpenLineage](https://openlineage.io/)",
        ],
    },

    # --- AIE (6) ---
    {
        "filename": "AI_Local_LLMs",
        "title": "🏠 LLMs en local — Ollama, vLLM, llama.cpp",
        "role": "AI Engineer · Wiki + Tutoriel",
        "dataset": "Prompts test custom",
        "intro": "Exécuter des LLMs en local : confidentialité, coût, offline. Stack 2026 : Ollama, llama.cpp, vLLM, SGLang.",
        "sections": [
            ("Pourquoi local",
             "Confidentialité (santé, juridique), coût (vs API par token), offline (terrain), latence (pas de network), customisation totale."),
            ("Modèles open-weights 2026",
             "Llama 3.x/4.x (Meta), Mistral / Mixtral, Qwen 3 (Alibaba), Gemma 3 (Google), Phi-4 (Microsoft), SmolLM2 (HF). Tailles : 0.5B → 405B."),
            ("Ollama — install + Python",
             "`ollama pull llama3.2`. API REST OpenAI-compatible. Library Python officielle. Modelfiles pour custom system prompts."),
            ("llama.cpp + GGUF",
             "Format GGUF (binaire compact, quantizé). `llama-cpp-python`. Run CPU/GPU/Metal/CUDA."),
            ("LM Studio (UI desktop)",
             "Pour les non-devs ou debug. Catalog de modèles."),
            ("vLLM — serveur prod",
             "Paged attention, continuous batching. Throughput 10-100× supérieur. OpenAI-compatible API."),
            ("SGLang — alternative haute perf",
             "RadixAttention (cache shared prefixes). Native function calling. Encore mieux que vLLM sur certains workloads."),
            ("MLX (Apple Silicon)",
             "Framework Apple optimisé pour M-series. `mlx-lm` pour LLMs."),
            ("TGI — Hugging Face",
             "Text Generation Inference. Production-grade. Bonne integration HF Hub."),
            ("Quantization",
             "4-bit GGUF Q4_K_M (sweet spot), AWQ (vLLM-compatible), GPTQ. Trade-off qualité vs taille / vitesse."),
            ("Benchmarks 2026",
             "Throughput (tokens/s), latency (TTFT - Time To First Token), batch size scaling, RAM/VRAM utilisation, quality on MT-Bench/IFEval."),
            ("Sécurité prompts + guardrails",
             "Prompt injection. NeMo Guardrails (NVIDIA), Guardrails AI, LLM Guard. Detection + sanitization."),
        ],
        "sources": [
            "[Ollama docs](https://ollama.com/)",
            "[llama.cpp GitHub](https://github.com/ggerganov/llama.cpp)",
            "[vLLM docs](https://docs.vllm.ai/)",
            "[SGLang docs](https://docs.sglang.ai/)",
        ],
    },

    {
        "filename": "AI_LLM_Finetuning_PEFT",
        "title": "🎚️ LLM Fine-tuning — PEFT, LoRA, DPO",
        "role": "AI Engineer + ML Engineer · Wiki + Tutoriel",
        "dataset": "Alpaca-fr ou Dolly-15k",
        "intro": "Fine-tuning de LLMs : quand, comment, avec quels outils 2026 (PEFT, TRL, Unsloth, Axolotl).",
        "sections": [
            ("Quand fine-tuner",
             "Decision tree : prompt engineering → RAG → fine-tune. Cas qui justifient fine-tune : style spécifique, format strict, latence (modèle plus petit), confidentialité."),
            ("Types de fine-tuning",
             "**SFT** (Supervised Fine-Tuning, instruction-tuning), **Reward Modeling**, **DPO** (Direct Preference Optimization), RLHF (PPO), distillation."),
            ("PEFT : LoRA / QLoRA / DoRA / AdaLoRA",
             "LoRA : matrices low-rank `ΔW = B A`. QLoRA : LoRA + base model quantizé 4-bit. DoRA : amélioration récente (magnitude + direction). AdaLoRA : rang adaptatif."),
            ("Hugging Face TRL",
             "Library officielle. `SFTTrainer`, `DPOTrainer`, `ORPOTrainer`. Integration `transformers`."),
            ("Unsloth — 2-5× plus rapide",
             "Optimisations mémoire + kernels Triton custom. Permet de fine-tuner Llama 70B sur 1 GPU 48 GB."),
            ("Axolotl — config YAML",
             "Wrapper TRL avec config déclarative. Standard pour les fine-tunes communautaires."),
            ("Pipeline complet",
             "Data prep (ChatML format) → SFT → DPO → eval → quantize (GGUF/AWQ) → deploy (vLLM/Ollama)."),
            ("Datasets formats",
             "ChatML : `{messages: [{role, content}]}`. ShareGPT, Alpaca, OpenAssistant. Synthetic via Evol-Instruct."),
            ("Eval",
             "LM Eval Harness (200+ tasks), MT-Bench (chat quality), AlpacaEval (head-to-head vs gpt-4), IFEval (instruction following), domain-specific."),
            ("Pièges",
             "Catastrophic forgetting, mode collapse (toutes les réponses identiques), length bias (DPO favorise long), data leakage train/eval."),
            ("Synthetic data",
             "Self-Instruct, Evol-Instruct, Distilabel (Argilla), generating from a strong teacher LLM."),
        ],
        "sources": [
            "[HuggingFace TRL](https://huggingface.co/docs/trl)",
            "[PEFT docs](https://huggingface.co/docs/peft)",
            "[Unsloth](https://github.com/unslothai/unsloth)",
            "[Axolotl](https://github.com/OpenAccess-AI-Collective/axolotl)",
            "Notebook lié : `NLP_Transformers`.",
        ],
    },

    {
        "filename": "AI_Agents_Tools",
        "title": "🤖 LLM Agents et Tool Use",
        "role": "AI Engineer · Wiki + Tutoriel",
        "dataset": "Tâches assistantes simulées (web search, calcul, code)",
        "intro": "Construire des agents LLM avec tool use : frameworks 2026, patterns, MCP, sécurité.",
        "sections": [
            ("Cadre agent",
             "LLM (cerveau) + tools (mains) + memory + planner + executor. Loop : observe → think → act."),
            ("Tool use natif",
             "OpenAI Function Calling, Anthropic Tools API, JSON Schema. Structured outputs. Limites et coûts."),
            ("Frameworks 2026",
             "**LangGraph** (state machine), **LlamaIndex Agents**, **AutoGen** (Microsoft, multi-agent), **CrewAI** (rôles spécialisés), **DSPy** (programmatique)."),
            ("ReAct pattern",
             "Yao 2022 : reasoning + acting interleaved. Thought → Action → Observation → Thought... Le pattern fondateur."),
            ("Reflexion / self-critique",
             "Shinn 2023 : agent qui critique sa propre réponse et itère. Améliore SWE-bench, AlfWorld."),
            ("Multi-agent",
             "Coordinator + workers spécialisés. Patterns : assembly line, parliament, debate. CrewAI / AutoGen."),
            ("MCP — Model Context Protocol",
             "Standard Anthropic 2024 pour les tools. Server exposant des fonctions, client (LLM) consommant. Découplage."),
            ("Computer use agents",
             "Anthropic Claude computer use (oct 2024). L'agent voit l'écran et clique. GPT operator. Cas d'usage et limites."),
            ("Memory",
             "Short-term (context window), long-term (vector DB, voir `BDD_Vectorielles`), episodic, semantic, procedural."),
            ("Évaluation",
             "Task success rate (binary), cost ($/task), latency, robustness, tool selection accuracy. Benchmarks : SWE-bench, ToolBench, AgentBench, BFCL."),
            ("Sécurité",
             "Sandbox tools, allowlist d'actions, validation outputs, prompt injection (jailbreak via tool output). LLM Guard, Prompt Shield."),
            ("Cas d'usage",
             "RAG agent (retrieve dynamique), coding agent (Aider, Devin, Cursor), web research agent (Perplexity), data analyst agent."),
        ],
        "sources": [
            "[LangGraph docs](https://langchain-ai.github.io/langgraph/)",
            "[MCP spec — Anthropic](https://modelcontextprotocol.io/)",
            "[AutoGen — Microsoft](https://github.com/microsoft/autogen)",
            "[DSPy](https://dspy.ai/)",
            "Notebook lié : `NLP_Recherche_d_informations`.",
        ],
    },

    {
        "filename": "AI_Prompt_Engineering",
        "title": "💬 Prompt Engineering — patterns 2026",
        "role": "AI Engineer · Wiki + Tutoriel",
        "dataset": "Tâches NLP variées (classif, extraction, raisonnement)",
        "intro": "Concevoir des prompts efficaces : structures, CoT, few-shot, structured output, DSPy.",
        "sections": [
            ("Cadre",
             "In-context learning : le LLM apprend sa tâche depuis le prompt. Zero-shot vs few-shot. Limites du context."),
            ("Anatomie d'un bon prompt",
             "Role / persona + Task + Examples + Output format + Constraints. Template `you are X. Do Y. Format : Z`."),
            ("Chain-of-Thought (CoT)",
             "Wei 2022 : 'Let's think step by step'. Augmente la perf sur raisonnement maths/logique."),
            ("Self-consistency",
             "Wang 2022 : générer N CoT, voter sur la réponse majoritaire. Plus robuste mais plus cher."),
            ("Tree-of-Thought (ToT)",
             "Yao 2023 : explorer plusieurs branches de raisonnement, pruning. Pour les problèmes combinatoires (jeu de 24, Sudoku)."),
            ("Skeleton-of-Thought",
             "Génère un plan, puis remplit chaque section en parallèle. Réduit la latence."),
            ("Constitutional AI",
             "Anthropic : guide le LLM par des principes (constitution). Self-critique + révision."),
            ("Structured output",
             "JSON mode (OpenAI), tool use (Anthropic). Libs : **Outlines**, **Instructor**, **Marvin** — forcent la sortie au schéma Pydantic via grammar-based decoding."),
            ("Few-shot example selection",
             "Choisir les exemples par similarité sémantique au prompt (via embeddings)."),
            ("Meta-prompts",
             "Prompts qui génèrent des prompts. Auto-amélioration. APE (Automatic Prompt Engineer)."),
            ("DSPy",
             "Programmer les prompts comme du code. Signatures = type-system. Compilers optimisent automatiquement les prompts/few-shots."),
            ("Évaluation",
             "`promptfoo` (regression tests), `langfuse` / `langsmith` (observabilité), `OpenAI Evals`, `LangSmith Datasets`."),
            ("Anti-patterns",
             "Ambiguïté (« écris bien »), contradictions, prompts trop longs (lost in the middle), instructions négatives."),
        ],
        "sources": [
            "[Prompt Engineering Guide — DAIR](https://www.promptingguide.ai/)",
            "[DSPy](https://dspy.ai/)",
            "[Instructor](https://python.useinstructor.com/)",
            "[Outlines](https://github.com/dottxt-ai/outlines)",
        ],
    },

    {
        "filename": "AI_Multimodal_VLM",
        "title": "👁️ Vision-Language Models (VLMs)",
        "role": "AI Engineer · Wiki + Tutoriel",
        "dataset": "COCO captions, sample images, screenshots",
        "intro": "Modèles multimodaux vision+texte : CLIP, LLaVA, Qwen-VL. Cas d'usage 2026.",
        "sections": [
            ("Cadre",
             "Vision Encoder (ViT) + LLM. Espace latent partagé (CLIP-style) ou cross-attention (LLaVA-style)."),
            ("CLIP / SigLIP / OpenCLIP",
             "Embeddings alignés image/texte par contrastive learning. Zero-shot image classification, retrieval cross-modal."),
            ("VLMs génératifs",
             "**LLaVA**, **Qwen-VL** (Alibaba), **Gemma 3** (multimodal natif), **Pixtral** (Mistral), **Molmo** (Allen AI), **SmolVLM** (HF)."),
            ("Document understanding",
             "LayoutLM, Donut (sans OCR), **ColPali** (retrieval natif sur PDFs scannés). Liens avec `DE_Docling`."),
            ("Video",
             "VideoLLaMA, InternVideo, Apollo. Plus de difficulté car séquence temporelle."),
            ("Cas d'usage",
             "Captioning, VQA, OCR-free document parsing, table extraction, chart understanding, agent qui voit l'écran (Claude computer use)."),
            ("Tool use multimodal",
             "Claude vision + tools, GPT-4V + function calling. Agent qui prend une screenshot et clique."),
            ("Fine-tuning",
             "LoRA sur LLaVA / Qwen-VL via TRL `SFTTrainer` (support multimodal 2024+). Datasets : LLaVA-Instruct, ShareGPT-4V."),
            ("Évaluation",
             "MMMU (Massive Multimodal Understanding), MMBench, ChartQA, DocVQA, RefCOCO."),
            ("Libs / serveurs 2026",
             "`transformers` (HF support VLMs), `vllm` (support multimodal), `unsloth` (fine-tune VLMs), Ollama (LLaVA local)."),
        ],
        "sources": [
            "[LLaVA project](https://llava-vl.github.io/)",
            "[ColPali](https://github.com/illuin-tech/colpali)",
            "[Qwen-VL](https://huggingface.co/Qwen)",
            "[MMMU benchmark](https://mmmu-benchmark.github.io/)",
        ],
    },

    {
        "filename": "AI_Speech_Audio",
        "title": "🔊 Speech & Audio AI",
        "role": "AI Engineer · Wiki + Tutoriel",
        "dataset": "LibriSpeech samples, librosa builtins",
        "intro": "ASR, TTS, diarization, embeddings audio, music generation. Stack open 2026.",
        "sections": [
            ("ASR — Automatic Speech Recognition",
             "**Whisper** (OpenAI 2022, multi-langues, ouvert), **Whisper-large-v3-turbo** (2024). Alternatives : Conformer (NeMo), Distil-Whisper. Streaming ASR."),
            ("TTS — Text-to-Speech",
             "**XTTS** (Coqui, voice cloning), **F5-TTS** (Microsoft 2024), **OpenVoice** (MyShell). SaaS : ElevenLabs, PlayHT."),
            ("Speaker diarization",
             "Qui parle quand. **pyannote** (référence), Whisper-X (Whisper + pyannote)."),
            ("Voice cloning",
             "Zero-shot voice cloning (XTTS-v2). **Considérations éthiques** : consent, deepfakes."),
            ("Speech embeddings",
             "wav2vec2 (Meta), HuBERT (Meta), WavLM (Microsoft). Pour speaker verification, accent classification, language ID."),
            ("Music generation",
             "**MusicGen** (Meta, conditionnel sur texte), **AudioGen**, **Stable Audio** (Stability AI), **Suno** (SaaS)."),
            ("Speech-to-speech",
             "**SeamlessM4T** (Meta), GPT-4o voice mode, Moshi (Kyutai). Latence ultra-faible."),
            ("Pipelines réels",
             "Meeting transcription (Whisper + pyannote), real-time dubbing, audiobook generation, voice assistants embedded."),
            ("Latence temps réel",
             "VAD (Voice Activity Detection), streaming inference, model quantization, batching."),
            ("Libs / outils 2026",
             "`whisper` (OpenAI), `whisper-cpp`, `faster-whisper` (CTranslate2), `pyannote`, `coqui-tts`, `bark`, `audiocraft` (Meta), `librosa`."),
        ],
        "sources": [
            "[Whisper paper](https://cdn.openai.com/papers/whisper.pdf)",
            "[pyannote-audio](https://github.com/pyannote/pyannote-audio)",
            "[Coqui-TTS](https://github.com/coqui-ai/TTS)",
            "[audiocraft (Meta)](https://github.com/facebookresearch/audiocraft)",
        ],
    },

    # --- MLE (4) ---
    {
        "filename": "MLE_Feature_Store",
        "title": "🗄️ Feature Store — Feast et alternatives",
        "role": "ML Engineer + MLOps · Wiki + Tutoriel",
        "dataset": "Cal Housing batch + features streaming",
        "intro": "Feature stores : éliminer le training-serving skew, gouverner les features, point-in-time correctness.",
        "sections": [
            ("Pourquoi un feature store",
             "Training-serving skew (features calculées différemment en train et en prod = bugs subtils). DRY across teams. Online vs offline."),
            ("Feast (open-source)",
             "Entities, FeatureView, FeatureService. Materialization batch (offline → online). Retrieval API."),
            ("Alternatives managées",
             "Tecton (ex-Uber), Hopsworks, AWS SageMaker Feature Store, Databricks Feature Store, GCP Vertex AI Feature Store."),
            ("Online vs offline store",
             "Online : Redis/DynamoDB/Cassandra (read latency ms). Offline : Parquet/BigQuery/Snowflake (batch analytics)."),
            ("Point-in-time correctness",
             "Le pire bug ML : utiliser une feature future au moment t. Le feature store enforce que toute query donne la valeur 'as-of' un timestamp."),
            ("Feature transformations",
             "Batch (Spark/dbt), on-demand (au moment du request, calculé live), streaming (Flink/Kafka)."),
            ("Streaming features",
             "Kafka → Flink → online store. Cas : nb_clicks_last_5min mis à jour en temps réel."),
            ("Discovery & gouvernance",
             "Feature registry, documentation, owner, tests. Comme un data catalog mais pour features ML."),
            ("Integration MLflow",
             "Logger les features utilisées par chaque run pour reproductibilité."),
            ("Quand pas de feature store",
             "< 10 modèles en prod, équipe < 5 personnes : surestimation. Préférer un dbt + bonnes pratiques."),
        ],
        "sources": [
            "[Feast docs](https://docs.feast.dev/)",
            "[Tecton docs](https://docs.tecton.ai/)",
            "[Feature Stores for ML (Hopsworks blog)](https://www.hopsworks.ai/)",
        ],
    },

    {
        "filename": "MLE_Online_Inference",
        "title": "⚡ Online Inference — Triton, BentoML, vLLM",
        "role": "ML Engineer · Wiki + Tutoriel",
        "dataset": "Cal Housing model + LLM model",
        "intro": "Servir des modèles en temps réel : latence, throughput, batching, quantization.",
        "sections": [
            ("Latence cible",
             "Real-time (<100ms typique), near-real-time (<1s), batch (>1s OK). Définir SLO."),
            ("Servers 2026",
             "**BentoML** (Python-native, multi-model), **NVIDIA Triton** (perf max, multi-framework), **TorchServe**, **TensorFlow Serving**."),
            ("ONNX Runtime / TensorRT",
             "Conversion modèle → ONNX → ONNX Runtime (CPU/GPU portable). TensorRT (NVIDIA-only, fastest). OpenVINO (Intel)."),
            ("Quantization",
             "int8 (4× plus rapide souvent), fp16, bf16, 4-bit (LLMs). Outils : `bitsandbytes`, `optimum`, `auto-gptq`."),
            ("Batching dynamique",
             "Combiner N requests entrantes en une batch pour mieux utiliser le GPU. Triton dynamic batching, vLLM continuous batching."),
            ("Caching de prédictions",
             "Hash des inputs, Redis. Énorme gain si même requête répétée (search query, image identique)."),
            ("A/B testing en prod",
             "Canary (1 % traffic), shadow deployment (vrai model + nouveau en parallèle, comparer), blue-green."),
            ("Monitoring latence",
             "P50, P95, P99. Histogrammes Prometheus + Grafana. Alerting si dégradation."),
            ("Auto-scaling Kubernetes",
             "KServe (CNCF), Seldon Core, Ray Serve. HPA sur métriques custom (request rate, GPU utilization)."),
            ("Cas LLMs",
             "vLLM / SGLang / TGI : paged attention, prefix caching, speculative decoding. KV cache management."),
        ],
        "sources": [
            "[BentoML docs](https://docs.bentoml.com/)",
            "[NVIDIA Triton docs](https://docs.nvidia.com/deeplearning/triton-inference-server/)",
            "[KServe](https://kserve.github.io/website/)",
            "Notebook lié : `MLE_Model_Serving`.",
        ],
    },

    {
        "filename": "MLE_Model_Serving",
        "title": "📦 Model Serving — packaging et déploiement",
        "role": "ML Engineer + MLOps · Wiki + Tutoriel",
        "dataset": "Modèle ML pré-entrainé",
        "intro": "Packager un modèle pour le déploiement : MLflow Models, BentoML, container, serverless.",
        "sections": [
            ("Packaging",
             "Modèle artifact + code d'inférence + deps + signature. Container Docker = standard reproductible."),
            ("MLflow Models (pyfunc)",
             "Format universel cross-framework. `mlflow.pyfunc.load_model(uri)`. Sert le modèle via `mlflow models serve`."),
            ("BentoML vs Cog vs Truss",
             "BentoML : Python-native, riche. Cog (Replicate) : YAML + Dockerfile auto. Truss (Baseten) : similaire à Cog."),
            ("KServe / Seldon",
             "Kubernetes-native serving. InferenceService CRD. Auto-scaling, canary, transformers."),
            ("Cloud SaaS",
             "AWS SageMaker, Vertex AI (GCP), Azure ML Endpoints, Databricks Model Serving. Pros : managed. Cons : lock-in, coût."),
            ("Serverless",
             "AWS Lambda (cold start), GCP Cloud Run, Modal, Replicate, Beam. Pour low-throughput intermittent."),
            ("API design",
             "Sync vs async, batch endpoint, streaming SSE pour LLMs. Versionning d'API (/v1, /v2)."),
            ("Versioning",
             "Modèles (MLflow), schemas (Pydantic), contrats (OpenAPI). Backward compatibility."),
            ("Rollback",
             "Always keep N-1 deployed. Feature flags pour switch instantané. Database migrations reversible."),
            ("Multi-modèle serving",
             "Gateway pattern : 1 API qui route vers N modèles selon header / payload. Bonne pratique pour A/B testing et fallback."),
        ],
        "sources": [
            "[MLflow Models](https://mlflow.org/docs/latest/models.html)",
            "[BentoML docs](https://docs.bentoml.com/)",
            "[Cog (Replicate)](https://github.com/replicate/cog)",
            "[KServe](https://kserve.github.io/)",
        ],
    },

    {
        "filename": "MLE_AB_Testing",
        "title": "🧪 A/B Testing — ML production",
        "role": "ML Engineer + Data Scientist · Wiki + Tutoriel",
        "dataset": "Synthetic conversion data",
        "intro": "A/B testing rigoureux pour valider l'impact business d'un nouveau modèle.",
        "sections": [
            ("Cadre A/B",
             "Hypothèse nulle H0 (les variantes ont même perf). Test bilatéral. p-value, puissance, MDE."),
            ("Sample size calculator",
             "Pour binary outcome (conversion) et continuous (revenue). Formules. Outils : Optimizely, Statsig."),
            ("Sequential testing",
             "Permet d'arrêter dès qu'on a un signal (vs fixed horizon). Always Valid Inference (mSPRT). Évite peeking."),
            ("CUPED",
             "Controlled-experiment Using Pre-Experiment Data (Microsoft 2013). Réduit la variance en utilisant un covariate pré-expé."),
            ("Multi-arm bandits",
             "Quand on veut optimiser online plutôt que tester rigoureusement. Lien `ML_Apprentissage_par_Renforcement`."),
            ("Bayesian A/B testing",
             "Posterior sur Δθ. `P(B > A | data)` directement interprétable business. Lien `DS_Bayesian`."),
            ("Stratification, blocking",
             "Garantir équilibre des covariates entre A et B (sex, geo, device). Réduit la variance."),
            ("Pièges",
             "Peeking (multiple comparisons), Simpson's paradox, network effects (mes amis voient B et m'influencent), novelty effects."),
            ("Outils 2026",
             "GrowthBook (OSS), Statsig, Optimizely, LaunchDarkly, Eppo. Compare : OSS vs SaaS, coût, fonctionnalités."),
            ("Cas spéciaux",
             "Long-term effects (carryover), holdout group permanent, expérimentation continue (rolling rollouts)."),
        ],
        "sources": [
            "[Trustworthy Online Controlled Experiments — Kohavi et al. (livre)](https://www.cambridge.org/)",
            "[GrowthBook docs](https://docs.growthbook.io/)",
            "[Statsig docs](https://docs.statsig.com/)",
            "Notebooks liés : `DS_Causal_Inference`, `DS_Bayesian`, `ML_Apprentissage_par_Renforcement`.",
        ],
    },

    # --- MLOps (4) ---
    {
        "filename": "MLOps_Pipelines_Airflow",
        "title": "🔄 Pipelines ML end-to-end (Airflow / Prefect)",
        "role": "MLOps · Tutoriel",
        "dataset": "Cal Housing pipeline ELT + ML",
        "intro": "Construire un pipeline ML production-grade orchestré.",
        "sections": [
            ("Workflow ML standard",
             "Ingestion → validation → preprocessing → train → eval → register → deploy → monitor. Boucle continue."),
            ("DAG Airflow / Prefect concret",
             "Code complet d'un pipeline mensuel : ingest from S3 → validate with GE → train via TaskFlow → register MLflow → deploy via KServe."),
            ("Idempotence + retry",
             "Toute task doit pouvoir être rejouée sans dommage. Patterns : INSERT IGNORE, upsert, checkpoint."),
            ("Branching",
             "Si nouvelles données détectées → train. Sinon → skip et notify."),
            ("Backfill",
             "Rejouer le passé sur les N derniers jours. Crucial après bug fix."),
            ("Secrets management",
             "Vault (HashiCorp), AWS Secrets Manager, Doppler. Jamais en clair dans le code."),
            ("Notifications",
             "Slack on failure, success summary daily. PagerDuty pour critiques."),
            ("Combine MLflow + Airflow",
             "Chaque DAG task logue dans la run MLflow appropriée. Mapping DAG_RUN_ID ↔ MLflow run_id."),
            ("CI/CD du pipeline",
             "Tester les DAGs avant déploiement. `airflow dags test`. Pre-commit hooks."),
            ("Alternatives",
             "Kubeflow Pipelines (K8s natif), Metaflow (Netflix), ZenML, Flyte. Lequel quand."),
        ],
        "sources": [
            "[Airflow docs](https://airflow.apache.org/docs/)",
            "[Prefect docs](https://docs.prefect.io/)",
            "[Kubeflow docs](https://www.kubeflow.org/)",
            "Notebook lié : `ML_MLFlow_Bench`.",
        ],
    },

    {
        "filename": "MLOps_Model_Registry",
        "title": "📚 Model Registry — gouvernance des modèles",
        "role": "MLOps · Wiki + Tutoriel",
        "dataset": "Cal Housing modèle",
        "intro": "Gérer le cycle de vie des modèles en prod : versions, aliases, approval, lineage.",
        "sections": [
            ("Pourquoi un registry",
             "Versioning, traçabilité, rollback, governance, compliance (AI Act 2024)."),
            ("MLflow Registry (review)",
             "Voir `ML_MLFlow_Bench`. Focus prod : aliases (@champion, @challenger), workflow promotion."),
            ("Weights & Biases Model Registry",
             "UI plus polie, integration W&B Sweeps. SaaS."),
            ("SageMaker Model Registry",
             "Tight integration avec SageMaker Endpoints. Approval workflow natif."),
            ("Workflow aliases détaillé",
             "@staging → tests automatiques → @challenger → A/B test → @champion (si meilleur). Rollback en 1 commande."),
            ("Approval workflows",
             "Pull request-like : un model doit être approuvé par data scientist + MLE + tech lead avant prod. Audit trail."),
            ("Lineage",
             "Modèle → run → dataset version (DVC) → code commit (git SHA). Indispensable pour reproductibilité et audit."),
            ("Sécurité",
             "RBAC (qui peut promote en prod), audit log (qui a fait quoi quand), modèles signés."),
            ("Compliance (AI Act EU 2024)",
             "Model cards obligatoires, datasheet (datasets), SBOM ML, risk assessment."),
            ("Pratiques 2026",
             "Versioner aussi : prompts (pour LLMs), tools (pour agents), datasets. Tout est immutable et versionné."),
        ],
        "sources": [
            "[MLflow Registry workflow](https://mlflow.org/docs/latest/ml/model-registry/workflow/)",
            "[Model Cards (Google paper)](https://arxiv.org/abs/1810.03993)",
            "[AI Act EU](https://artificialintelligenceact.eu/)",
            "Notebook lié : `ML_MLFlow_Bench`.",
        ],
    },

    {
        "filename": "MLOps_Drift_Monitoring",
        "title": "📉 Drift Monitoring — Evidently, NannyML",
        "role": "MLOps · Wiki + Tutoriel",
        "dataset": "Cal Housing train vs simulated prod (avec drift injecté)",
        "intro": "Détecter dégradation modèle en prod : data drift, concept drift, performance.",
        "sections": [
            ("Pourquoi monitorer",
             "Modèles dégradent avec le temps : data distribution change, monde change. Détection avant que ça pète."),
            ("Types de drift",
             "**Covariate drift** : `P(X)` change. **Label drift** : `P(Y)` change. **Concept drift** : `P(Y|X)` change. Conséquences différentes."),
            ("Tests statistiques",
             "Kolmogorov-Smirnov (continu), Chi² (catégoriel), PSI (Population Stability Index — seuils 0.1, 0.2), Wasserstein."),
            ("Evidently AI",
             "Lib OSS référence 2024+. Reports HTML interactifs. Tests intégrés. Integration MLflow / Prefect / Airflow."),
            ("NannyML",
             "Performance estimation **sans ground truth** (CBPE — Confidence-Based Performance Estimation). Quand les labels arrivent en retard ou jamais."),
            ("SaaS : WhyLabs / Arize / Fiddler",
             "Observabilité ML cloud. Inclut feature attribution, fairness, root cause analysis."),
            ("Monitoring inference",
             "Latency (P50/P95/P99), throughput, error rate, GPU utilization, memory. Prometheus + Grafana standard."),
            ("Business metrics",
             "CTR, conversion, revenue. Le vrai but. Aligner ML metrics avec business metrics (parfois pas corrélés)."),
            ("Alerting",
             "Slack, PagerDuty, email. Thresholds adaptifs (z-score sur historique). Anti-spam : grouping, deduplication."),
            ("Stratégie de retraining",
             "Trigger-based (drift détecté), scheduled (chaque semaine), adaptive (continual learning), shadow validation avant rollout."),
        ],
        "sources": [
            "[Evidently AI](https://docs.evidentlyai.com/)",
            "[NannyML](https://nannyml.readthedocs.io/)",
            "[Arize AI](https://docs.arize.com/)",
            "[ML Drift Detection (Microsoft Learn)](https://learn.microsoft.com/)",
        ],
    },

    {
        "filename": "MLOps_CICD_GitHub_Actions",
        "title": "🔁 CI/CD pour ML avec GitHub Actions",
        "role": "MLOps · Tutoriel",
        "dataset": "Repo ML demo",
        "intro": "CI/CD adapté au ML : datasets, modèles, gates de qualité.",
        "sections": [
            ("Spécificités CI/CD ML",
             "vs CI/CD classique : datasets (versioner, large), modèles (binary, lourd), reproductibilité (seed, deps), eval (pas juste tests unitaires)."),
            ("GitHub Actions — workflows",
             "Fichier `.github/workflows/ml.yml`. Triggers : push, PR, schedule, manual."),
            ("Steps types pipeline",
             "Lint (ruff/black) → tests unitaires (pytest) → data tests (Great Expectations) → train (sur runner GPU si dispo) → eval → register MLflow → deploy si meilleur."),
            ("CML — Continuous Machine Learning",
             "Iterative.ai lib qui ajoute des comments dans PR avec metrics, graphes, comparaison vs baseline."),
            ("DVC integration",
             "Versioner datasets et modèles dans le repo via pointers. `dvc pull` dans CI pour récupérer."),
            ("Self-hosted runners GPU",
             "Cluster perso ou cloud (CML provisione automatiquement EC2 GPU)."),
            ("Secrets & OIDC",
             "GitHub OIDC → assume role AWS sans long-lived credentials. Best practice 2024+."),
            ("Cache",
             "Cache pip dependencies, modèles téléchargés, datasets DVC. Gain énorme."),
            ("Tests de modèle",
             "Behavioral tests (CheckList), robustness (perturbations), fairness (Fairlearn), regression (vs previous best)."),
            ("Comparatif",
             "GitHub Actions vs GitLab CI vs Jenkins vs CircleCI vs Buildkite. Pour ML : GitHub Actions + CML = standard 2026."),
            ("Deployment gates",
             "Reviewers requis pour merger en main. Environments protected (prod). Manual approval avant deploy."),
        ],
        "sources": [
            "[GitHub Actions docs](https://docs.github.com/en/actions)",
            "[CML — Iterative](https://cml.dev/)",
            "[DVC docs](https://dvc.org/)",
            "Notebooks liés : `ML_MLFlow_Bench`, `MLOps_Pipelines_Airflow`.",
        ],
    },
]


def main() -> None:
    print(f"Génération de {len(NOTEBOOKS)} notebooks dans {OUT_DIR}/...")
    for nb in NOTEBOOKS:
        path = OUT_DIR / f"{nb['filename']}.md"
        content = build_notebook(
            title=nb["title"],
            role=nb["role"],
            dataset=nb["dataset"],
            intro=nb["intro"],
            sections=nb["sections"],
            sources=nb["sources"],
        )
        path.write_text(content, encoding="utf-8")
        print(f"  OK {nb['filename']}.md ({len(content)} chars)")

    print(f"\nGénération terminée : {len(NOTEBOOKS)} notebooks créés.")


if __name__ == "__main__":
    main()
